# Site settings
baseURL = "https://example.com"
languageCode = "en-US"
title = "Estudio Industria 4.0"
theme = "hugo-split-theme-master"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2021 Fundecor"

[params]

  # Metadata for search engines and social sharing
  author = "Fundecor"
  description = "ANÁLISIS DEL ESTADO DE SITUACIÓN DE LAS EMPRESAS DE AUTOMATIZACIÓN INDUSTRIAL PARA EL DESARROLLO DE ACCIONES CONJUNTAS PARA LA CREACIÓN DE UN HUB DE INNOVACIÓN"
  shareImage = "images/background1.jpg"
  #twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background1.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  
  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
