# Site settings
baseURL = "https://www.fundecor.es/estudio-industria40/"
languageCode = "en-US"
title = "ANÁLISIS DEL ESTADO DE SITUACIÓN DE LAS EMPRESAS DE AUTOMATIZACIÓN INDUSTRIAL EN LA PROVINCIA DE CÓRDOBA"
theme = "hugo-split-theme-master"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]
relativeURLs = true
uglyURLs = true


# Enter your tracking code to enable Google Analytics
googleAnalytics = ""



[params]

  # Metadata for search engines and social sharing
  author = "Fundecor"
  description = "Industria 4.0"
  shareImage = "images/social.jpg"
 

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background1.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = ""
      # youtubeId = "dk9uNWPP7EA"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
